language: go
sudo: false
go:
 - 1.4.2
 - master
os:
 - linux
 - osx
install:
  - go get .
script:
  - go build
deploy:
  - provider: releases
    api_key:
      secure: R4xxz1QwZlkXP3jFKqCnIW/IdGCBpaKJ9dPm53PM1cHcovvIJtY/ZJXS+e1Vs1zwCODhj6AN7BjyysS/YLVs2SV7G9YgjZECKnINXVIGnNGefutWuKho2uXFBBU25pXe10/GjvadlJDA7lbAKJoL0mDi0RituksIx6K+rDheOSI=
    file: branch-release
    skip_cleanup: true
    on:
      tags: true
      repo: securingsincity/branch-release